apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-dashboard
  namespace: default
  labels:
    app: mq-dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-dashboard-app
  template:
    metadata:
      labels:
        app: mq-dashboard-app
    spec:
      containers:
        - name: mq-dashboard-container
          image: <image-url-ECR>
          ports:
            - containerPort: 3000
              name: mq-dashboard-port

---

apiVersion: v1
kind: Service
metadata:
  name: mq-dashboard
  labels:
    app: mq-dashboard-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: mq-dashboard-port
      nodePort: 30000
  selector:
    app: mq-dashboard-app